// This file was generated by Expo SDK 51.0.25. DO NOT MODIFY.

// Fallback for using MaterialIcons on Android and web.

import MaterialIcons from '@expo/vector-icons/MaterialIcons';
import { SymbolWeight } from 'expo-symbols';
import { ComponentProps } from 'react';
import { OpaqueColorValue, type StyleProp, type TextStyle } from 'react-native';

/**
 * Add your SF Symbols to Material Icons mappings here.
 * - see Material Icons in the [Icons Directory](https://icons.expo.fyi).
 * - see SF Symbols in the [SF Symbols](https://developer.apple.com/sf-symbols/) app.
 */
const MAPPING = {
  'chart.bar': 'bar-chart',
  'chevron.left.forwardslash.chevron.right': 'code',
  'chevron.right': 'chevron-right',
  'creditcard': 'credit-card',
  'doc.text': 'swap-horiz',
  'doc.text.fill': 'receipt-long',
  'gearshape': 'settings',
  'house': 'home',
  'paperplane': 'send',
  'wallet': 'account-balance-wallet',
  'swap-horiz': 'swap-horiz',
  'calendar': 'calendar-today', // Add calendar icon mapping
  'magnifyingglass': 'search', // Add search icon mapping
  'pencil': 'edit', // Add pencil/edit icon mapping
  'trash': 'delete', // Add trash/delete icon mapping
  'person.fill': 'person', // Add person icon mapping
} as const;

type IconSymbolName = keyof typeof MAPPING;

/**
 * An icon component that uses native SF Symbols on iOS, and Material Icons on Android and web.
 * This ensures a consistent look across platforms, and optimal resource usage.
 * Icon `name`s are based on SF Symbols and require manual mapping to Material Icons.
 */
export function IconSymbol({
  name,
  size = 24,
  color,
  style,
  weight,
}: {
  name: IconSymbolName;
  size?: number;
  color: string | OpaqueColorValue;
  style?: StyleProp<TextStyle>;
  weight?: SymbolWeight;
}) {
  return <MaterialIcons color={color} size={size} name={MAPPING[name]} style={style} />;
}